---
Serilog:
  MinimumLevel:
    Default: Information
    Override:
     Microsoft: Error
     System: Error
  WriteTo:
  - Name: Console
  - Name: File
    Args:
      path: Logs/log.txt
      outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} | {ThreadId} | {Level:u4} | {AppDomain} | {SourceContext} | {Message:lj}{NewLine}{Exception}"
      rollingInterval: Day
      fileSizeLimitBytes: 10485760
      rollOnFileSizeLimit: true
      retainedFileCountLimit: 10
  Enrich:
  - FromLogContext
  - WithThreadId
IbmMQ:
    QueueManagerName: GA02.AR.T.QM
    Channel: ITG.TO.GA02.TEST
    ConnectionInfo: "192.6.6.39(1416)"
    QueueName: QL.BORRARME.REQ